Post, Travel CRUD 및 테스트 작성.
Kernel360/f1-Yigil pull request #145
Opened 2024-01-10 03:08 UTC by ShineCorine

## Motivation 🧐
우리 서비스의 메인 비지니스 로직인 게시글과 경로, 스팟에 대한 기본적인 CRUD 작성에 대한 API 및 동작 생성
-

<br>

## Key Changes 🔑
Post 도메인가 Travel 도메인의 CRUD 기능과 테스트 작성
멀티 모듈 변경에 따른 패키지 리팩토링 진행
<br>

## To Reviewers 🙏
DB 리플리케이션 적용 이후로 CRUD 테스트를 하지 못했습니다.
잘 부탁드려요!

2024-01-10 05:08 UTC, stoneHee99 requested changes
모든 정적 메서드를 사용할 때 간편하다 말고는 장점을 모르겠는데, 객체지향의 장점들이 많이 깨지게 되는 것 같구... 특히 객체 생성과 관련된 부분에서는 static 키워드를 사용할 필요성을 잘 못느끼는데 왜 static을 썼는지 궁금합니다!

2024-01-10 05:08 UTC, stoneHee99 commented on backend/yigil-api/src/main/java/kr/co/yigil/travel/dto/SpotInCourseDto.java
> +        return new SpotInCourseDto(spot.getTitle(), spot.getFileUrl(), spot.getDescription());
여기도 왜 스태틱 메서드로 from 메서드를 생성했는지 궁금합니다. 그냥 생성자를 쓰면 더 좋을 것 같다고 느껴져서요!

2024-01-10 05:14 UTC, ShineCorine commented on backend/yigil-api/src/main/java/kr/co/yigil/post/application/PostService.java
> +        List<Post> posts = postRepository.findAll();
이슈에 올리고 반영하도록 하겠습니다!

2024-01-10 05:32 UTC, Uknow928 commented on backend/yigil-api/src/main/java/kr/co/yigil/post/application/PostService.java
> +        post.setIsDeleted(false);
transaction 안에서 jpa  변경감지를 통해 자동으로 업데이트되는 것으로 알고있습니당

2024-01-11 02:01 UTC, Uknow928 approved these changes

2024-01-11 02:05 UTC, merged