댓글 기능 추가
Kernel360/f1-Yigil pull request #160
Opened 2024-01-17 02:39 UTC by ShineCorine

## Motivation 🧐
- 게시글 댓글을 위한 도메인을 추가합니다.

<br>

## Key Changes 🔑
- 댓글 작성, 조회, 삭제 api 추가
- 댓글 개수 정보 redis 캐싱 적용
- 테스트 코드 작성
<br>

## To Reviewers 🙏
- 실수하거나 잘못된 것 있으면 가감없이 말씀해주세요
-  to chatgtp: 5줄 이하로 요약해줘

2024-01-17 02:58 UTC, stoneHee99 requested changes

2024-01-17 02:58 UTC, stoneHee99 commented on backend/yigil-api/src/main/java/kr/co/yigil/comment/domain/Comment.java
> +    private List<Comment> children = new ArrayList<>();
comment 엔티티가 항상 Children 리스트 까지 들고다닐 필요가 있을까요? 제 생각에는 꼭 필요한 컬럼이 아닌 것 같이 느껴지기도 해서 의도가 궁금해요!
그리고 soft delete를 구현하셨는데 children 속성의 orphanRemoval을 걸어놓은게 실제 엔티티 연관관계가 끊어졌을 때를 대비해서 만들어놓으신 의도한 부분인지도 궁금합니다

2024-01-17 02:58 UTC, stoneHee99 commented on backend/yigil-api/src/main/java/kr/co/yigil/comment/domain/Comment.java
> +    public void setParent(Comment parent) {
작성하신 setParent 메서드는 순환참조의 위험성이 생길 수 있을 것 같아요.
@JsonIgnoreProperties 등을 사용할 필요가 있을 것 같아요.
또 setter 메서드를 활용해서 객체의 값을 변경하기 보다는 factory 메서드를 만들어서 새로운 인스턴스를 만드는 방향이 더 엔티티 신뢰성을 높이는 방향인 것 같아요

2024-01-17 02:58 UTC, stoneHee99 commented on backend/yigil-api/src/main/java/kr/co/yigil/comment/domain/CommentCount.java
> +    public void decrementCommentCount(int deletedCommentCount) { commentCount-=deletedCommentCount;}
위 domain entity 객체에서 본 것으로는 부모 엔티티가 삭제되어도 하위 댓글은 남아있는 상태인데, 해당 분의 Comment count를 모두 삭제한다면 문제가 발생할 것 같아요.

2024-01-17 02:58 UTC, stoneHee99 commented on backend/yigil-api/src/main/java/kr/co/yigil/comment/domain/repository/CommentRepository.java
> +//    List<Comment> findCommentListByPostId(@Param("postId") Long postId);
이런 주석 부분은 pr 날릴땐 최대한 없애서 올려주시면 좋을 것 같아요.

2024-01-17 02:59 UTC, minson96 approved these changes
확인했습니다~!!

2024-01-17 03:18 UTC, ShineCorine commented on backend/yigil-api/src/main/java/kr/co/yigil/comment/domain/Comment.java
> +    public void setParent(Comment parent) {
아하 그렇네요. 순환참조 문제 전혀 생각을 못하고 있었습니다.

```
Comment newComment = new Comment(commentCreateRequest.getContent(), member, post);

        if (commentCreateRequest.getParentId() != null && commentCreateRequest.getNotifiedMemberId() != null) {
            Comment parentComment = findCommentById(commentCreateRequest.getParentId());
            newComment.setParent(parentComment);

            Member notifiedMember = memberService.findMemberById(commentCreateRequest.getNotifiedMemberId());
            sendCommentNotification(notifiedMember, newComment.getContent());
        }
```
이 부분에서 단순 comment를 생성하고 parent가 있을 경우 parent를 추가하는 식으로 했는데, 
그럼  위의 Comment newComment = new Comment(commentCreateRequest.getContent(), member, post);
부분을 if 안에서 parent를 생성해서 같이 new로  부모 댓글이 있는 comment를 만들고 else로는 없는 댓글을 만드는 식으로 하겠습니다!

2024-01-19 01:31 UTC, Uknow928 approved these changes

2024-01-19 01:36 UTC, merged