마이 페이지의 마이 페이지 부분 구현
Kernel360/f1-Yigil pull request #175
Opened 2024-01-23 09:57 UTC by davidktlee

## Motivation 🧐
마이 페이지의 마이페이지 부분을 스타일링과 기능 구현 완료했습니다.
<br>

## Key Changes 🔑
`with-header` 디렉토리 내부에 마이 페이지 디렉토리 생성 및 레이아웃 생성
<br>

## To Reviewers 🙏
현재 디자인이 단순 그레이 배경인데 장소에 대한 사진이 올 경우 어두운 사진 일 경우 글씨가 잘 보이지 않을 수도 있다는 생각이 들었습니다.
현재 `My / 저장` 과 `장소 / 일정` 을 모두 `useState`로 처리하고 있는데 라우팅 처리하는 게 더 나은 방법일지 state를 사용하는 게 좋은 방법일 지 고민이 됩니다.

2024-01-23 14:59 UTC, hatchling13 requested changes
실패하는 테스트 코드 수정 부탁드립니다.
또한, `(with-header)/(mypage)`와 `(mypage)`와 같이 Route Group을 사용할 경우 동일한 디렉토리명을 사용하는 형태로 코드를 작성하면(예시: `mypage/page.tsx`) 생성되는 Path가 같아져 실행이 되지 않습니다.

2024-01-23 14:59 UTC, hatchling13 commented on frontend/src/app/(mypage)/layout.tsx
`(with-header)`안에 있는 것들과 그냥 `(mypage)` 안에 있는 것들과는 무슨 차이가 있는 건가요?

2024-01-23 14:59 UTC, hatchling13 commented on frontend/src/app/_components/mypage/MyPageInfo.tsx
`useSession` hook의 경우, 이후에 `getServerSession`을 통해 최적화할 여지가 있을 것으로 예상합니다.

2024-01-23 17:25 UTC, minson96 approved these changes
확인했습니다~!!

2024-01-24 01:42 UTC, davidktlee commented on frontend/src/app/(mypage)/layout.tsx
머지 진행 했을 때 기존에 존재했던 (mypage)를 제거하지 못했습니다. 수정하겠습니다.

2024-01-24 06:45 UTC, hatchling13 approved these changes

2024-01-24 06:45 UTC, hatchling13 commented on frontend/src/app/_components/mypage/MyPageContent.tsx
백엔드에서 제공하는 API가 얼마나 세분화되어있는지에 따라 client state를 선택할지 routing을 선택할지를 고려해야 한다고 생각합니다.

렌더링할 데이터의 수가 일정 이하인 경우에는 실제 렌더링보다 네트워크 IO가 사용자 경험에 더 큰 영향을 미친다고 알고 있습니다.

백엔드에서 한번에 전체 데이터를 쏴주는 경우에는 state에 따라 적절히 골라서 렌더링하면 될 것 같습니다.
그러나 만약 `MY`와 `저장` 관련 API 콜이 서로 별개의 형태로 분리된 경우, 라우팅을 통해 서버 컴포넌트를 활성화한 다음 각각의 API 콜을 node 단에서 처리하여 사용자에게 보내주는 방법이 더 좋을 것 같습니다.

이 부분은 이후 백엔드 파트와 API 관련 논의를 거쳐 결정하는 편이 나아보입니다.

2024-01-24 06:45 UTC, hatchling13 commented on frontend/src/app/_components/mypage/MyPlace.tsx
이 부분도 `MyPageContent.tsx`에서 이야기했던 바와 동등하게 생각할 수 있겠습니다.
특히 useEffect를 통해 data를 fetch하는 형태는 App Router에서 그리 권장되지 않는 형태인 것 같아 눈여겨볼 필요가 있다고 생각합니다.

2024-01-24 06:45 UTC, merged