헤더 리팩토링
Kernel360/f1-Yigil pull request #185
Opened 2024-01-25 09:12 UTC by davidktlee

## Motivation 🧐
헤더의 스타일 변경과 session 사용 방식을 변경했습니다.

## Key Changes 🔑
 헤더에서 `useSession`이 화면이 렌더링 되고 난 후 렌더링 되는 불편한 부분이 있었는데 서버 세션으로 로직을 변경하면서 코드가 상당수 줄어들고 화면이 되기 전에 확인할 수 있게 되었습니다.
헤더의 상위 컴포넌트에 높이를 주었을 때 헤더가 줄어드는 현상이 나타나 지정 높이 대신 padding y 를 적용했습니다.
아래로 스크롤 했을 때 `embla carousel`이 헤더 위로 올라오는 현상이 나타나 `z-index`도 추가했습니다.

## To Reviewers 🙏

2024-01-25 15:02 UTC, hatchling13 requested changes
`PopOver` 컴포넌트의 위치와 크기 관련 이슈가 해결되어야합니다.

2024-01-26 01:20 UTC, davidktlee commented on frontend/src/app/_components/ui/popover/PopOver.tsx
> +      <div className="absolute bottom-[-90px] right-4 w-[134px] h-[104px] bg-[#F3F4F6] rounded-md flex flex-col items-center justify-center gap-5">
아 맞습니다. 현재로썬 위치가 고정되어 있어 수정하도록 하겠습니다.

2024-01-26 01:35 UTC, davidktlee commented on frontend/src/app/_components/ui/popover/PopOver.tsx
> +interface PropsType {
<img width="502" alt="스크린샷 2024-01-26 오전 10 27 31" src="https://github.com/Kernel360/f1-Yigil/assets/97086762/f8e7e8fe-b3d2-4fa3-832c-869f272efca3">

props를 export 함으로써 외부에서 가져다 쓸 때 타입 자동 완성이 된다는 말씀을 잘 이해하지 못했습니다.
위의 사진은 타입을 export 하지 않은 상황에서 popoverData에 hover했을 때 뜨는 타입인데 export 했을 때 기대할 수 있는 타입 자동 완성과 다른 부분이 있다면 공유 부탁드리겠습니다!
그리고 저는 `~Type`이라고 주로 정하긴 하는데 접두사에 `T`로 컨벤션을 정한다면 전혀 문제 없이 사용할 수 있을 것 같습니다.
`T`를 붙여서 사용하는 방식으로 정하고 노션의 네이밍 컨벤션에 기록해 두겠습니다.

2024-01-26 02:58 UTC, hatchling13 commented on frontend/src/app/_components/ui/popover/PopOver.tsx
> +interface PropsType {
논의 후 현재 상황에서는 필요없음이 합의되어, 추후 API 변경사항이 있을 경우 수정하는 쪽으로 생각하면 되겠습니다.

2024-01-26 03:18 UTC, hatchling13 commented on frontend/src/app/_components/ui/popover/PopOver.tsx
> +      <div className="absolute bottom-[-90px] right-4 w-[134px] h-[104px] bg-[#F3F4F6] rounded-md flex flex-col items-center justify-center gap-5">
논의 후, `width`와 `height`를 제거하는 방향으로 합의하였습니다. 이외의 스타일은 좋습니다!

2024-01-26 03:21 UTC, hatchling13 approved these changes
좋습니다~

2024-01-26 04:10 UTC, stoneHee99 approved these changes

2024-01-26 04:10 UTC, merged