Popover 웹 접근성을 위한 esc 키 다운 이벤트 추가
Kernel360/f1-Yigil pull request #191
Opened 2024-01-27 02:02 UTC by davidktlee

## Motivation 🧐
popover의 웹 접근성을 위해 팝 오버 열렸을 때 탭으로 접근 후 esc 눌렀을 때 팝 오버 닫히는 기능 추가
<br>

## Key Changes 🔑
팝 오버의 link 태그에 onKeyDown 이벤트 추가
<br>

## To Reviewers 🙏
탭으로 접근했을 때 프로필 이미지도 접근 가능하게 만들어야 할까요?
현재는 마우스 말고 키보드만으로는 프로필 이미지에는 focus가 되지 않는 상태입니다.

2024-01-27 20:25 UTC, hatchling13 requested changes
키보드 접근을 신경쓴다면 탭으로 프로필 이미지에도 접근 가능하게 만들어야 한다고 생각합니다.
해당 부분은 `onClick`이 달려있는 부분에 `tabIndex={0}`을 넣어주면 되지 않을까 합니다.
해당 코드 추가 후 탭으로 탐색해본 결과, `RoundProfile` 컴포넌트 자체에 margin이 들어가있어 focus 영역이 어색하게 잡히는 현상이 있습니다.

2024-01-27 20:25 UTC, hatchling13 commented on frontend/src/app/_components/ui/popover/PopOver.tsx
> +        onKeyDown={(e) =>
현재 구현 상으로는 Tab 키를 한 번 더 눌러서 focus가 PopOver 내의 특정 메뉴로 옮겨졌을 때에만 이벤트 버블링을 통해 `div`에 적용된 `onKeyDown` 핸들러가 실행되어, 최종적으로 PopOver가 닫히는 형태입니다. 궁극적으로는 팝오버가 열린 직후에도 ESC 키를 통해 닫음 처리되어야 하는 게 올바른 동작이라고 생각합니다.

여러모로 건드려본 결과 저는 마땅한 해결법을 못 찾았습니다...

2024-01-28 06:57 UTC, davidktlee commented on frontend/src/app/_components/ui/popover/PopOver.tsx
> +        onKeyDown={(e) =>
위의 말씀주신 `tabIndex` 추가 하였으며 `margin` 속성도 컴포넌트에 주는 것이 아닌 외부에서 주는 걸로 변경했습니다!
헤더의 이미지의 `onClick`달려 있는 `span` 태그에 `onKeyDown` 이벤트를 이용해 `Enter`로 여는 것과 `Esc`로 닫는 부분 구현해보았는데 한 번 확인 부탁드립니다.

2024-01-28 11:26 UTC, hatchling13 approved these changes
좋은 것 같습니다!

마지막으로, 크리티컬한 부분은 아니지만 모달이 열렸을 때 모달 아래에 가려진 부분도 탭으로 탐색할 수 있는 것이 어색하게 느껴질 수도 있습니다. 이 부분은 아마 단순 코드 수정으로는 힘들 수도 있어서 [react-focus-lock](https://github.com/theKashey/react-focus-lock)같은 라이브러리들이 많이 권장됩니다만, 현재 상황에서는 이 부분에 너무 많이 공수를 들이지 않아도 괜찮을 것 같습니다.

2024-01-29 01:59 UTC, ShineCorine approved these changes

2024-01-29 06:09 UTC, merged