리뷰 컴포넌트
Kernel360/f1-Yigil pull request #211
Opened 2024-01-31 13:44 UTC by davidktlee

## Motivation 🧐
장소 추가와 일정 추가에서 사용되는 리뷰 컴포넌트를 작성했습니다.
상위 컴포넌트에서 `viewTitle` 이라는 불리언 값으로 제목 폼의 `visible`여부를 처리하고
`reviewState` 라는 상태와  `setReviewState` 라는 set 함수를 이용해 제목과 리뷰의 내용을 set 합니다.

## Key Changes 🔑

<br>

## To Reviewers 🙏
- 글자를 입력할 때마다 set 함수가 실행되는 것을 방지하기 위해 [디바운스](https://velog.io/@davidktlee/%EB%94%94%EB%B0%94%EC%9A%B4%EC%8A%A4Debounce)를 적용하려 했으나 리뷰 폼 아래에 존재하는 글자 수를 보여주는 디자인 때문에 디바운스 적용 시 어색함을 느낄 우려가 있어 적용하지 않았습니다. 
- 현재 `input`과 `textarea`에 `required` 옵션을 줬으나 같은 컴포넌트에서 버튼을 클릭했을 때만 동작하는 걸로 예상합니다. (다른 컴포넌트에 존재하는 다음 버튼을 눌렀을 때 어떻게 동작할지 모르겠습니다.)
그래서 디자인에 존재하는 다른 컴포넌트의 다음 버튼을 눌렀을 때 빈 값에 대한 검증을 해줘야 할 것 같습니다.
디자인에 `validation`에 대한 디자인도 요청드리고 싶지만 시간 관계 상 구현이 우선인 것 같아 말씀은 드리지 않았습니다.

2024-01-31 18:05 UTC, hatchling13 requested changes
코드에 별다른 문제는 없지만, 별점 쪽의 애니메이션은 적용할 필요가 있다고 생각합니다. 저에게는 차이가 좀 크게 느껴졌거든요.

2024-01-31 18:05 UTC, hatchling13 commented on frontend/src/app/_components/add/common/PostReview.tsx
> +          maxLength={29}
최대 30자인데 `maxLength`가 29인 이유가 있나요?

2024-02-01 02:13 UTC, davidktlee commented on frontend/src/app/_components/add/common/PostReview.tsx
> +          maxLength={29}
영어로 작성할 경우 30자까지 딱 맞게 떨어지는데 한글로 작성할 경우 31자까지 넘어가는 현상이 발생해서 그렇게 설정했습니다!

2024-02-01 02:22 UTC, davidktlee commented on frontend/src/app/_components/add/common/PostRating.tsx
애니메이션 적용해보도록 하겠습니다.

2024-02-01 02:46 UTC, hatchling13 commented on frontend/src/app/_components/add/common/PostReview.tsx
> +          maxLength={29}
<img width="423" alt="스크린샷 2024-02-01 오전 11 23 42" src="https://github.com/Kernel360/f1-Yigil/assets/8166749/452ce426-e294-4bf8-99bc-ab3fc7fbaf42">

이런 상태를 말씀하시는거죠? CJK 입력의 특수성 때문에 일어나는 문제인 것 같습니다.
`onChangeReview`에 아래의 코드를 적용하여 한국어/영어 여부에 관계없이 원하는 결과를 얻을 수 있었습니다.

```ts
const onChangeReview = (e: EventFor<'input' | 'textarea', 'onChange'>) => {
  const { name, value } = e.currentTarget;

  const maxLengthAttribute = e.target.getAttribute('maxlength');

  if (!maxLengthAttribute) {
    return;
  }

  const maxLength = Number.parseInt(maxLengthAttribute, 10);

  if (name === 'review' && e.target.value.length > maxLength) {
    e.target.blur();
    e.target.focus();

    return;
  }

  setReviewState({ ...reviewState, [name]: value });
};
```

textarea의 현재 입력값이 최대값보다 큰지 비교하여 만약 크다면 blur 후 다시 focus하는 코드이며, 이를 통해 최대 길이까지 입력되었을 경우 중간 입력 단계를 없애줍니다.

2024-02-01 03:17 UTC, davidktlee commented on frontend/src/app/_components/add/common/PostReview.tsx
> +          maxLength={29}
![image](https://github.com/Kernel360/f1-Yigil/assets/97086762/edd6ab70-4bcf-4be2-9621-8c719eca5d28)
정욱님 코드를 보고 좋은 것 같아서 응용해서 작성해보았습니다.
onChangeReview라는 함수가 한 단어가 입력될 때마다 실행되는데 그 때마다 `maxLength` 속성을 가져오고 변수를 생성하는 것보다는 상위에 `maxLength` 변수를 생성하고 `input` 속성에도 그 변수를 할당, 함수 내부에서도 그 변수를 사용해 조건문을 처리하는 식으로 처리했습니다.

2024-02-01 03:44 UTC, stoneHee99 approved these changes

2024-02-01 03:45 UTC, hatchling13 approved these changes

2024-02-01 03:45 UTC, merged