Home FAB 기능 추가 및 포탈 추가
Kernel360/f1-Yigil pull request #225
Opened 2024-02-02 10:35 UTC by davidktlee

## Motivation 🧐
기존에 정욱님이 작업해주셨던 FAB에 기능 및 애니메이션을 추가했습니다.
기존 존재하던 pop over 컴포넌트를 react의 `createPortal` 함수를 이용해 감싸 z-index에 크게 의존하지 않는 pop over 및 FAB를 구현했습니다.

## Key Changes 🔑
기존의 pop over는 현재 페이지에서 단순히 위에 div 태그를 이용해 윗 부분을 덮는 구현이었는데 그러다 보니 `z-index`로 레이어를 컨트롤 해야하는 상황이 발생했고 예기치 않은 버그가 발생했습니다.
pop over에 넘겨주던 `setIsModalOpened` 함수가 단순히 `false`값만 받는 함수였기 때문에  `modalClose` 함수로 감싸 가독성 좋고 한가지 역할만 하는 함수로 처리했습니다.

[wiki](https://github.com/Kernel360/f1-Yigil/wiki)에 발생했던 상황과 코드를 남겨두었습니다.
<br>

## To Reviewers 🙏

2024-02-02 10:36 UTC, ShineCorine approved these changes

2024-02-03 07:55 UTC, hatchling13 requested changes
기능이 잘 작동하는 걸 보니 너무 좋네용! 👍 👍 👍 
컴포넌트 구조만 좀 수정하면 좋을 것 같습니다.

2024-02-03 07:55 UTC, hatchling13 commented on frontend/src/app/_components/Portal.tsx
> +            <PopOver
현재 구현대로라면 `PopOver`와 `ViewPortal`의 결합도가 너무 강합니다. `PopOver`를 그리고 싶은데 사용해야 하는 컴포넌트는`ViewPortal`이 되기 때문에 의미론적으로도 약간 아귀가 맞지 않습니다. 다음과 같은 식의 구현 방향성이 옳지 않을까요?

```jsx
// Portal.tsx
function ViewPortal({ ..., backdropStyle, children} : { ..., children: ReactNode /* 또는 ReactElement */ }) {
  const [element, setElement] = useState<HTMLElement | null>(null);

  // useEffect code...

  return createPortal(<div className={backdropStyle}>{children}</div>, element);
}

// PopOver.tsx
function PopOver({ ..., position, backdropStyle }) {
  return <ViewPortal backdropStyle={backdropStyle}>
    <nav className={position}>
      { /* ... */ }
    </nav>
  </ViewPort>
}

// PopOver 쓰는 곳
function SomeComponent() {
  const [isModalOpened, setIsModalOpened] = useState(false);

  // ...

  return <div>
    {isModalOpened && <PopOver {/* ... */} position='{위치 속성}' backdropStyle='{백드롭 속성}'  />}
  </div>
}
```

2024-02-03 07:55 UTC, hatchling13 commented on frontend/src/app/_components/Portal.tsx
> +  return (
의미없는 `Fragment`는 지우는 것이 좋을 것 같습니다!

2024-02-03 10:39 UTC, davidktlee commented on frontend/src/app/_components/Portal.tsx
> +            <PopOver
동의합니다. portal을 확인 모달이라던지 다른 모달을 띄울 때도 사용할 수도 있는데 너무 범용성 낮은 컴포넌트로 만든 것 같네요.
구조 변경 후 푸시하겠습니다.

2024-02-03 14:58 UTC, hatchling13 reviewed
의문 사항 달아놓았습니다! 해당 부분 해결되면 승인하겠습니다~

2024-02-03 14:58 UTC, hatchling13 commented on frontend/src/app/_components/ui/popover/PopOver.tsx
>    return (
`PopOver`에서 렌더되는 최상위 컴포넌트를 `ViewPortal`로 하는 건 마음에 안드시나용? `PopOver` 쓰는 곳마다 `ViewPortal`은 항상 같이 들어가야되는데 현재 상태로라면 `ViewPortal` 쓰는 걸 까먹고 그냥 쓰다가 오류 만나는 경우가 더 많을 것 같다는 생각이 듭니다.

2024-02-03 15:00 UTC, hatchling13 requested changes
생각해보니 이번에 구조를 바꾸면서 `HeaderClient`에 들어가있는 팝 오버 컴포넌트 사용법이 갱신되어있지 않았던 걸 발견해서, 이 부분도 반영해주셔야 합니다~

2024-02-03 15:12 UTC, davidktlee commented
> 생각해보니 이번에 구조를 바꾸면서 `HeaderClient`에 들어가있는 팝 오버 컴포넌트 사용법이 갱신되어있지 않았던 걸 발견해서, 이 부분도 반영해주셔야 합니다~

맞습니다 현재 반영중에 있고 pop over컴포넌트의 타입을 좀 더 넓게 유연하게 받기 위해 제네릭을 사용하는 방법을 고민중에 있습니다.

2024-02-03 15:18 UTC, davidktlee commented on frontend/src/app/_components/ui/popover/PopOver.tsx
>    return (
말씀대로 pop over를 사용할 때는 항상 portal과 사용되니 같이 사용을 하도록 pop over 컴포넌트에 위치시키는 것도 좋은 것 같습니다.

2024-02-03 15:34 UTC, davidktlee commented
팝 오버 컴포넌트가 다양한 `props`를 받을 수도 있을 것 같아서 제네릭을 이용해 타입을 넓혀 보려 했는데 결국 `PopOverIcon`에서 props를 사용하는 과정에서 제네릭을 이용하는 의미가 없다는 생각이 들어 제네릭 도입은 하지 않았습니다.

2024-02-03 16:03 UTC, hatchling13 approved these changes
👍

2024-02-03 16:03 UTC, merged