Http request 로직 수정
Kernel360/f1-Yigil pull request #261
Opened 2024-02-16 22:36 UTC by davidktlee

## Motivation 🧐
`http request` 요청 시 쿠키 설정이 안되는 이슈로 [서버액션](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations)으로 변경합니다.

## Key Changes 🔑
기존 http-request 로직에 `use server` 구문을 추가해 서버 액션으로 만들었습니다.

## To Reviewers 🙏
현재 클라이언트 요청, 서버 요청 다 잘되는 상황이고, 클라이언트에서는 useEffect 문 내 및 공식 문서처럼 onClick 이벤트로 테스트 해봤습니다.

2024-02-17 10:09 UTC, hatchling13 requested changes
`endpoints/api/auth/[...nextauth]/route.ts` 부분을 한번 확인해주십사 하여 우선 변경 요청 넣어놓겠습니다! 경택님 환경에서 동작하지 않는다면 승인 요청 답글 달아주셔요!

2024-02-17 10:09 UTC, hatchling13 commented on frontend/src/app/_components/api/httpRequest.ts
모든 요청은 로그인 상태 또는 로그아웃 상태로 나누어지고, 둘은 곧 `Cookie`에 `SESSION` 키-값 쌍이 있냐 없냐이기 때문에, `headers`를 나머지 입력값들보다 먼저 넣어줄 수 있으면 좋지 않을까요?

`requestWithSession` / `requestWithoutSession` 으로 나누어져, 매번 header에 쿠키 값을 넣어줄 필요가 없게 한다면 좀 더 편할 것 같이 보이는데, 확인해보려면 고쳐야되는 코드가 너무 많아져서 확인은 못해봤습니다.

2024-02-17 10:09 UTC, hatchling13 commented on frontend/src/app/endpoints/api/auth/[...nextauth]/route.ts
> +        const [key, value] = res.headers
어차피 server action을 통해 Node를 거치면 next가 가지고 있는 헤더값에 접근할 수 있는 게 아닌가? 해서 혹시나 싶어 쿠키 세팅하는 코드를 지우고 실행해봤는데 놀랍게도 제 환경에서는 동작하더라구요... 저희가 엉뚱한 곳에서 삽질을 하고 있었는지도 모르겠습니다ㅠㅠ

2024-02-17 10:09 UTC, hatchling13 commented on frontend/src/app/_components/api/httpRequest.ts
이 부분은 당장 반영해주지 않으셔도 됩니다! 이후 리팩토링할 시간이 있을 때 고쳐도 될 것 같아요.

2024-02-17 10:36 UTC, hatchling13 commented
이 PR이 성공적으로 merge된다면 배포를 위해 추가하신 URL도 문제없이 지울 수 있겠습니다!

2024-02-18 09:45 UTC, davidktlee commented on frontend/src/app/_components/api/httpRequest.ts
이 부분은 저도 고민했었던 부분이라 추후 반영하도록 하겠습니다!

2024-02-18 09:46 UTC, davidktlee commented on frontend/src/app/endpoints/api/auth/[...nextauth]/route.ts
>  const handler = NextAuth({
네 로그인 과정만 작업하려고 했으나 로그인과 밀접하게 연결된 부분이기 때문에 추가하도록 하겠습니다.

2024-02-18 09:48 UTC, davidktlee commented on frontend/src/app/endpoints/api/auth/[...nextauth]/route.ts
> +        const [key, value] = res.headers
`route.ts` 파일에서 set 쿠키를 해주는 과정을 생략하셨다는 말씀이실까요?
제 환경에서는 로그인 말고 다른 api request 보낼 때 next에서 만들어주는 쿠키는 잘 들어가는데 백엔드 서버로부터 받아온 `SESSION` 이라는 쿠키 값은 요청 헤더에서 어려운 것 같은데 좀 더 상세한 설명 부탁드려도 될까요?

2024-02-18 10:31 UTC, hatchling13 commented on frontend/src/app/endpoints/api/auth/[...nextauth]/route.ts
> +        const [key, value] = res.headers
아이고 이 부분은 제 환경에 지워지지 않았던 쿠키가 남아있어서 그랬었네요. 테스트를 위해 로그아웃 시에 쿠키를 지워주는 코드를 임시로 추가해놨었는데 해당 코드가 지워진 후 테스트를 한 번 더 해보다가 잘 되어서 왜지? 하고 놀라서 리뷰를 달았었습니다. 이 부분은 고려하지 않으셔도 됩니다!

2024-02-18 10:34 UTC, hatchling13 commented on frontend/src/app/endpoints/api/auth/[...nextauth]/route.ts
> +        cookies().set(key, value);
쿠키를 등록해줄 때 별도로 `HttpOnly`나 `SameSite` 설정을 해줘야할 것 같습니다.

```ts
cookies().set({
  name: key,
  value,
  httpOnly: true,
  sameSite: 'strict',
  secure: true,
});
```
로컬에서 시도했을 때는 잘 되긴 하는데 추후 배포할 때 문제가 있을 수 있으니 이후에 반영하면 좋겠습니다.

2024-02-20 02:17 UTC, minson96 approved these changes
확인하겠습니다.

2024-02-21 01:52 UTC, davidktlee commented
@hatchling13 백엔드 테스트 결과 `Cookie`를 헤더에 직접 넣지 않으면 백엔드에는 전달되지 않는 것으로 확인되어 http 요청을`httpRequestWithCookie / httpRequestWithoutCookie` 로 나누어 작성해놓겠습니다.

2024-02-21 02:43 UTC, ShineCorine approved these changes

2024-02-21 02:47 UTC, hatchling13 approved these changes
고생 많으셨습니다~ 관련해서 더 문제가 생기지 않았으면 좋겠는데요 ㅋㅋ

2024-02-21 02:47 UTC, hatchling13 commented on frontend/src/app/endpoints/api/auth/[...nextauth]/route.ts
> +      if (res) cookies().set('SESSION', '');
`res`는 성공한 상태든 실패한 상태든 항상 존재하지 않나용? 로그아웃 요청이 실패했을 때 세션 키를 삭제하려면 `res.ok`가 왔을 때 `set`해주는 게 맞을 것 같긴 한데, 문제는 브라우저 상에서 유지되는 next-auth의 세션과 백엔드가 가지고 있는 세션이 별개의 상태라는 점으로 보입니다.

signOut을 호출한 순간 백엔드에서 성공하든 실패하든 next-auth가 처리하는 session은 사라져서 어쨌든 사용자가 사용할 수 없겠죠? 프론트엔드 입장에서는 무조건 성공한다고 봐야될 것 같아서 수정 요청 드리려다 일단 승인하겠습니다.

2024-02-21 02:47 UTC, merged