style: 버튼 비활성화시에도 보이는 문제 해결
Kernel360/f1-Yigil pull request #317
Opened 2024-02-28 16:12 UTC by davidktlee

## Motivation 🧐
페이지네이션 버튼 비활성화 중에도 버튼이 보이는 현상을 수정했습니다
<br>

## Key Changes 🔑

<br>

## To Reviewers 🙏

2024-02-28 17:03 UTC, hatchling13 requested changes

2024-02-28 17:03 UTC, hatchling13 commented on frontend/src/app/_components/mypage/Pagination.tsx
> +          tabIndex={currentPage !== 1 ? 0 : -1}
첫 페이지 또는 마지막 페이지임에 따라 버튼을 렌더링하지 않게 만드시는 거라면 굳이 `tabIndex`를 설정하지 않으셔도 좋겠습니다! 버튼은 기본적으로 focusable하니까용~

2024-02-28 17:03 UTC, hatchling13 commented on frontend/src/app/_components/mypage/Pagination.tsx
> +            renderPage.includes(totalPage) && currentPage !== totalPage ? -1 : 0
위의 내용과 같습니다~

2024-02-28 23:38 UTC, davidktlee commented on frontend/src/app/_components/mypage/Pagination.tsx
> +          tabIndex={currentPage !== 1 ? 0 : -1}
그렇네욥 반영했습니다!

2024-02-29 01:52 UTC, hatchling13 approved these changes
👍

2024-02-29 02:59 UTC, minson96 approved these changes
확인했습니다

2024-02-29 03:03 UTC, merged