접근 제한 복구
Kernel360/f1-Yigil pull request #329
Opened 2024-02-29 17:56 UTC by hatchling13

## Motivation 🧐
접근 제한 코드를 수정된 로그인 방식에 맞게 수정하여 복구합니다.

## Key Changes 🔑
- 장소/추가, 마이페이지 관련 페이지에 로그인하지 않고 접근했을 경우, 로그인 페이지로 리다이렉트하기

## To Reviewers 🙏

2024-02-29 18:07 UTC, davidktlee requested changes
#324 부분에서 `middleware` 부분에서 이야기 나눴던 `set cookie` 부분을 확실하게 확인하고 그 부분이 없어도 브라우저에서 쿠키가 확인된다면 접근하는 url을 `restricted`로 제한하는 것 보다는 `nextjs`의 [`matcher`](https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher)를 사용하는 것이 좋지 않을까 생각합니다.

2024-02-29 18:40 UTC, hatchling13 commented
한 번 테스트해보시겠어요? 저는 저 부분 없으면 서버에 올렸을 때 쿠키를 못 받아온다고 생각해서, 해당 부분 확인되시면 추가 답 달아주시면 좋겠습니다.

2024-03-01 09:01 UTC, stoneHee99 approved these changes

2024-03-01 09:05 UTC, davidktlee commented
배포 후의 작업에 대한 부분이라 어떻게 확인해야할 지 모르겠네요.. 여유가 있을 때 확인해보는게 좋을 것 같습니다

2024-03-01 09:07 UTC, davidktlee approved these changes

2024-03-01 10:07 UTC, hatchling13 commented
프로덕션 서버에 올라가게 되면 dev 서버 쪽에서 확인해볼 수 있겠습니다!

2024-03-01 11:24 UTC, merged