주변 지도 검색
Kernel360/f1-Yigil pull request #417
Opened 2024-03-07 08:30 UTC by davidktlee

## Motivation 🧐
홈 페이지에 존재하는 주변 탭을 클릭 했을 때 나오는 지도 부분을 구현했습니다.
지도가 처음에 렌더링 될 때 위치 정보 허용 여부를 묻고 "허용"을 하면 로딩 후 현 위치로 이동됩니다.
현 위치를 기반으로 주변에 장소가 5개씩 요청되는 구조이고 장소가 5개 이상이면 페이지네이션으로 이동이 가능합니다.
지도를 이동 시켰을 때 장소를 불러오는 동안 로딩이 뜨도록 구현했습니다.
지도를 이동 시켰다가 다시 내 위치로 이동할 수 있게 현 위치 컨트롤러를 구현했습니다.
<br>

## Key Changes 🔑

<br>

## To Reviewers 🙏
주변 장소 마커를 클릭 후 한번 더 클릭해야 장소 상세 페이지로 이동하는데 "한번 더 클릭"에 대한 정보가 부족한 것 같아 토스트를 구웠습니다.(토스트 ui 추가)
백엔드와 이야기를 나눠 클러스터링을 구현해야 합니다.
- 지도 레벨에 따라 받아올 데이터를 결정 및 받아온 데이터를 기반으로 클러스터링 표시

2024-03-07 08:40 UTC, ShineCorine approved these changes

2024-03-07 08:57 UTC, hatchling13 requested changes
지도 이동 시에 장소를 불러오며 생기는 로딩 상태 UI는 필요한 부분이지만, 짧은 시간 내에 생겼다 사라지는 flickering 현상은 사용자 경험에 다소 부정적일 수도 있다고 합니다. 차후에 해당 부분을 어떻게 처리할 지 생각할 필요가 있습니다.

이외 수정 사항은 반영해주시면 되겠습니다!

2024-03-07 08:57 UTC, hatchling13 commented on frontend/src/app/_components/near/hooks/nearActions.ts
> +    `http://3.34.236.45:8080/api/v1/places/near?minX=${minX}&minY=${minY}&maxX=${maxX}&maxY=${maxY}&page=${page}`,
해당 부분의 `BASE_URL`은 `getBaseUrl()`을 통해 얻어올 수 있습니다.

2024-03-07 08:57 UTC, hatchling13 commented on frontend/src/app/_components/naver-map/CustomControl.tsx
> +  const locationBtnHtml = `
해당 버튼을 사용하지 않는다는 말씀을 구두로 전달해주신 바 있습니다. 수정해주시면 되겠습니다!

2024-03-07 08:57 UTC, hatchling13 commented on frontend/src/app/_components/add/common/AddSpotMap.tsx
hooks로 별도로 분리해 깔끔해져서 좋습니다! 👍

2024-03-07 08:57 UTC, hatchling13 commented on frontend/src/app/_components/naver-map/MapPagination.tsx
> +  const addPage = () => {
`add`/`minus`라는 이름보다는 사용자가 사용하는 방식인 '이전'/'다음'을 나타내는 단어를 사용하는 게 좋지 않을까 생각합니다!

2024-03-07 08:57 UTC, hatchling13 commented on frontend/src/app/_components/near/ViewTravelMap.tsx
> +  let timer: NodeJS.Timeout;
`'use client';` 구문이 들어갔다면 브라우저에서 그려지는 컴포넌트일텐데 `NodeJS.Timeout`을 사용하신 이유가 있을까요?

2024-03-07 09:03 UTC, davidktlee commented on frontend/src/app/_components/near/hooks/nearActions.ts
> +    `http://3.34.236.45:8080/api/v1/places/near?minX=${minX}&minY=${minY}&maxX=${maxX}&maxY=${maxY}&page=${page}`,
반영하겠습니다~!

2024-03-07 09:03 UTC, davidktlee commented on frontend/src/app/_components/naver-map/MapPagination.tsx
> +  const addPage = () => {
반영하겠습니다~!

2024-03-07 09:10 UTC, davidktlee commented on frontend/src/app/_components/near/ViewTravelMap.tsx
> +  let timer: NodeJS.Timeout;
`timer`에 대한 타입을 정의해줘야 해서 `NodeJS.Timeout`으로 줬는데 찾아보니  `returnType` 제네릭을 이용해  `setTimeout`의 타입 설정을 해줄 수 있네요.
수정 후 반영하겠습니다!

2024-03-07 09:15 UTC, hatchling13 reviewed
눈으로 보기에 코드 상으로는 문제를 찾기 힘든데, `npm run build`를 해보면 뭔가 걸리는 것들이 좀 있네요... 귀찮으시겠지만 한 번만 더 확인해주시겠어요?

2024-03-07 14:56 UTC, davidktlee commented
> Member

귀찮다니요 물론입니다! 확인하고 다시 pr올리겠습니다!

2024-03-08 03:32 UTC, hatchling13 requested changes
수정하신 이후 맵에서 로딩 상태가 변경되지 않는 것으로 확인됩니다! 한 번 봐주셔야 할 것 같아요

2024-03-08 05:24 UTC, hatchling13 commented on frontend/src/app/_components/near/ViewTravelMap.tsx
> +      setMaxMinBounds((v) => ({ ...v, maxX, maxY, minX, minY }));
어차피 `maxX`, `maxY`, `minX`, `minY`를 한 번에 외부(네이버 맵 컴포넌트)에서 다 받은 후 해당 값들로 `maxMinBounds` 값을 설정해주는데 굳이 현재 상태에 기반한 값 수정이 필요할까 하는 생각은 듭니다. 제가 시도해봤을 때는 그냥 `setMaxMinBounds({ maxX, maxY, minX, minY });`로만 해줘도 잘 돌아갔는데, 이렇게 써야 하는 이유가 있나요?

2024-03-08 05:39 UTC, davidktlee commented on frontend/src/app/_components/near/ViewTravelMap.tsx
> +      setMaxMinBounds((v) => ({ ...v, maxX, maxY, minX, minY }));
0 값인데 현재 상태에 기반한 수정이 필요하지는 않을 것 같습니다.
객체 상태이다 보니 습관적으로 썼던 것 같네요!
수정 후 반영하겠습니다!

2024-03-08 05:45 UTC, davidktlee commented
초기에 내 위치 로딩 전에 주변 장소 `api` 를 호출하는 부분을 조건을 추가하여 호출 하지 않도록 수정했습니다

2024-03-08 05:58 UTC, hatchling13 approved these changes
고생 많으셨습니다~

2024-03-08 05:58 UTC, merged