내가 등록한 장소 상세와 코스 상세 화면
Kernel360/f1-Yigil pull request #625
Opened 2024-03-24 13:20 UTC by davidktlee

## Motivation 🧐
내가 등록한 장세 상소 화면과 코스 상세 화면을 구현했습니다.
로그인 한 경우에 내가 등록한 장소일 경우 수정 창을 나타내게 했으며 수정이 가능합니다.

<br>

## Key Changes 🔑
image를 드래그해서 변경하던 `ImageContainer` 부분에서 dnd context의 중첩으로 인해 드래그 오버레이가 잘 동작하지 않는 이슈가 있었고, 
정욱님의 도움으로 `createPortal`을 통해 해결했습니다.
이미지를 지우려고 살짝만 클릭해도 이동되는 현상이 있어  `activationConstraint`의 `distance`를 1로 변경했습니다.
spot 수정 시에도 `getRouteGeoJson` 함수를 사용하기 위해 함수의 파라미터를 `place` 자체로 넘기던 값에서 상위에서 `place`의 `coords`를 얻어내 전달하는 것으로 변경했습니다.
기존의 `select` 컴포넌트에서 option으로 전달하는 값이 `number | string`였어서 `typeof`로 검증을 해줬어야 하는데 기존에 예상했던 `rate` 부분에서 `string`으로 넘겨줄 수 있어, `select` 컴포넌트 수정 후 `typeof` 를 쓰는 부분을 전체적으로 수정했습니다.
<br>

## To Reviewers 🙏
modify 하는 부분을 단순 state로 구분해 렌더링 하고 있는데, 리팩토링 시간이 있다면 전체 컴포넌트를 다 분리해서 가독성 좋게 코드를 수정해보고 싶네요.
똑같이 렌더링 되는 반복되는 부분을 줄이려고 단순 state로 처리했는데 만들고 보니 가독성이 떨어지는 것 같은 느낌이 듭니다.

2024-03-24 13:24 UTC, minson96 approved these changes
오예!

2024-03-24 15:15 UTC, hatchling13 requested changes

2024-03-24 15:15 UTC, hatchling13 commented on frontend/src/app/_components/mypage/course/CourseDetail.tsx
> +  const onClickDeleteSpot = (e: EventFor<'span', 'onClick'>, id: number) => {
`X` 버튼을 눌러도 해당 장소가 삭제되지 않습니다. `spotIdOrder` 내용 수정이 들어가야 하는 부분인가보네요?

2024-03-24 15:15 UTC, hatchling13 commented on frontend/src/app/_components/mypage/course/CourseDetail.tsx
> +              sizes="100vw"
최대 화면 너비가 `430px`이므로, 100vw(뷰포트 전체 너비)는 너무 큰 값이라고 생각합니다.

2024-03-24 15:15 UTC, hatchling13 commented on frontend/src/app/_components/mypage/hooks/myPageActions.ts
> +export const patchSpotDetail = async (
Spot과 Course 모두에 대해 적용되는 오류가 존재합니다.

첫 번째 이미지를 삭제하고 새로운 이미지를 추가하면 간헐적으로 서버 에러가 발생했다고 뜹니다.
이미지가 하나 있을때는 거의 항상 발생하고, 그 이상일 때는 떴다가 안떴다가 합니다... 굉장히 어려운 오류네요

2024-03-25 00:56 UTC, davidktlee commented on frontend/src/app/_components/images/ImagesContainer.tsx
> +    useSensor(PointerSensor, { activationConstraint: { distance: 1 } }),
0.01을 의도하신 것 같아 최대한 많이 변화를 안주려고 했습니다!
1px 했을 때도 잘 되었던 것 같은데 5로 변경하셨다면 그게 더 좋은 것 같습니다.
수정해놓겠습니다.

2024-03-25 00:56 UTC, davidktlee commented on frontend/src/app/(with-header)/detail/[travel]/[id]/page.tsx
> +import React from 'react';
컴포넌트 처음 생성 시 자동완성으로 생성하는데 그러다보니 생기는 것 같습니다,,

2024-03-25 01:07 UTC, davidktlee commented on frontend/src/app/_components/mypage/course/util.ts
그렇네요,, 이번에라도 도입할 걸 그랬습니다..

2024-03-25 01:15 UTC, davidktlee commented on frontend/src/app/_components/mypage/course/CourseDetail.tsx
> +  const onClickDeleteSpot = (e: EventFor<'span', 'onClick'>, id: number) => {
네 `filter`도 잘 안되고 있었네요!
수정하겠습니다

2024-03-25 02:18 UTC, davidktlee commented on frontend/src/app/_components/mypage/hooks/myPageActions.ts
> +export const patchSpotDetail = async (
백엔드와 얘기 후 백엔드쪽 에러인 것을 확인했고 수정 조치 받았습니다.

2024-03-25 02:18 UTC, davidktlee commented on frontend/src/app/_components/mypage/course/CourseDetail.tsx
> +              sizes="100vw"
기존에 이미지 최적화 하면서 이야기 나눴었는데 저희 사이트 최대 너비가 `430px`인데 `nextjs`에서 너무 많은 사이즈의 이미지를 생성하고 있어서,
next 설정의 `images`의 `deviceSizes`를 갤럭시 폴드를 폴드했을 경우의 제일 작은 사이즈 `280`, 가장 클 경우 `430` 두 사이즈를 설정해 놓겠습니다.
기존에 `100vw`에 대해 생성하던 이미지들이 최대 `430px` 이내의 이미지만 생성하는 것을 확인했습니다.

2024-03-25 02:46 UTC, davidktlee commented on frontend/src/app/_components/mypage/course/CourseSpotItem.tsx
> +            <span className="self-end text-gray-400 font-medium">
파이어폭스 브라우저 이슈인 것으로 확인했고, 수정 조치 하겠습니다!

2024-03-25 04:45 UTC, hatchling13 approved these changes
고생 많으셨습니다~

2024-03-25 04:56 UTC, merged