장소 상세 내용 추가
Kernel360/f1-Yigil pull request #644
Opened 2024-03-25 16:20 UTC by hatchling13

## Motivation 🧐
장소 상세 화면에 미비했던 여러 기능들을 추가합니다.

## Key Changes 🔑
- 장소 상세 화면에서 Spot을 추가할 수 있는 화면으로 갈 수 있도록 합니다.
- Spot/Course 전체에 대해 댓글 작성 / 좋아요를 할 수 있게 되었습니다.
- 더보기 버튼을 추가해 Spot/Course에 대한 댓글을 여러 개 가져올 수 있게 하였습니다.

## To Reviewers 🙏
신고, 팔로우/언팔로우, 대댓글 기능이 구현되지 않은 상태입니다.

2024-03-25 16:32 UTC, minson96 approved these changes
확인했습니다!

2024-03-26 01:30 UTC, minson96 approved these changes
확인했습니다

2024-03-26 02:32 UTC, davidktlee requested changes
타입만 수정해주시면 승인 하겠습니다!

2024-03-26 02:32 UTC, davidktlee commented on frontend/src/types/response.ts
>    create_date: z.coerce.date().transform((date) => date.toLocaleDateString()),
`toLocaleDateString` 인수로 코리아 타임이 들어가야 될 것 같습니다!

2024-03-26 02:53 UTC, davidktlee approved these changes
👍

2024-03-26 02:56 UTC, merged